// Generated by CoffeeScript 1.9.0
(function() {
  var destination, fs, gather, options, program, source;

  program = require('commander');

  fs = require('fs');

  fs.path = require('path');

  gather = require('./');

  program.usage('<directory> [options]').option('-o, --output <path>', 'Write the gathered data to a file.').option('-r, --raw', 'Do not add any metadata, keep the JSON as-is.').option('-a --annotate', 'Merge in additional metadata about the file.').option('-s --scheme [compact|underscored|extended]', 'The naming scheme for metadata fields [compact].', 'compact').option('-f, --force', 'Do not attempt to use any existing file at --output as a cache.').option('-I, --indent [n]', 'Indent the output JSON.', parseInt, 2).parse(process.argv);

  if (program.raw && program.annotate) {
    throw new Error("Cannot output raw and annotated data at the same time. Choose one.");
  }

  source = program.args[0];

  destination = program.output;

  options = {
    raw: program.raw,
    annotate: program.annotate,
    scheme: program.scheme,
    cache: program.force ? false : destination
  };

  gather(source, options, function(err, data) {
    var serialization;
    serialization = JSON.stringify(data, void 0, program.indent);
    if (destination) {
      return fs.writeFileSync(destination, serialization, {
        encoding: 'utf8'
      });
    } else {
      return console.log(serialization);
    }
  });

}).call(this);
